// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktxnppezwuiulgmbmeip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0eG5wcGV6d3VpdWxnbWJtZWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMjQ2OTMsImV4cCI6MjA0OTcwMDY5M30.Qnp_w7f8PFBHjBZEjbpHnT3Yc_bZaqEU1m67IBhhlEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);